---
restylers:
  - pyment:
      enabled: false
  - clazy:
      enabled: false
  # Disable conflicting python linters.
  # Conflicts with "isort"
  - reorder-python-imports:
      enabled: false
  # Conflicts with "black"
  - yapf:
      enabled: false
  - "*"
