---
language: generic
dist: xenial
os: linux

cache:
  directories:
    - "$HOME/.stack"

script:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --no-terminal install hlint pandoc stylish-haskell happy
  - travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-7.10.3.tar.bz2 | tar -xj -C $HOME/.local/bin
  - cp -a bin $HOME/.local/
  # TODO(iphydf): Figure out how to do this more generically. How were we supposed
  # to know that this file is needed and can be found here?
  - cp $HOME/.stack/snapshots/x86_64-linux/*/8.8.2/share/x86_64-linux-ghc-8.8.2/hlint-2.2.11/hlint.yaml $HOME/.local/bin/data/
  - (WORK=`pwd` && cd $HOME && tar zcf $WORK/hs-tools-$TRAVIS_TAG.tar.gz -C $HOME
      .local/bin
      .stack/snapshots/x86_64-linux/*/8.8.2/share/x86_64-linux-ghc-8.8.2/happy-1.19.12
      .stack/snapshots/x86_64-linux/*/8.8.2/share/x86_64-linux-ghc-8.8.2/hlint-2.2.11
      .stack/snapshots/x86_64-linux/*/8.8.2/share/x86_64-linux-ghc-8.8.2/pandoc-2.9.1.1)

deploy:
  provider: releases
  token:
    secure: "ZvPVLh17t3hU/hRO3zB9CCCRGdA1OQuMRBGSEd48BqSJJS44nbnyDsnW7hnFzXS8v3hJAUYXh9QrWDJvMvRUR6Up7cIXbVPqgcjJjpHrK7Gw6zCExCoJuR3lI7cM9IBZ46x5TvupmK8Xujb8InLvE1GlHjRWlCPLL+05ZVCannYHkhnq/yx99s0nQdu5YVPiqmDstl7i58xlqd2Of8grbc4ezjrA7U3EILpnzQWZK01BtTe6w4P9ICuNS4MlzYyTVg1F1rTJOoxUJh8l/X59E5ro1g+X84visBVBz+JAufvNb1DJO61Ozm4X8U4D64CRETvpyqGGm2bgRYdHzgVyqIe8shLlxXaZejMxx6EqSKX8l6Z5833KZSZgcS+7J2xxvFemQIROe2ad9LFSwmrv0NF6rD9+0CAYd0h+zOB03jkZ54sjz0O1y5CRsvkQVjpQYXx2Ib9Ilp8HS5c11mTgcvgrTk/6cMwwo572rN4QK/lLB5turrXESx5jwHuU2UezfME7MzTm5oEQqxXUhs83p2xH371WlihnC3yqWnMDm03A6VAjPJ3dmadAl5LKdjZKua4RQuN+YPOJFjqigiCtTy6MQamboOg/HfukzpZXCNpBCU++F8w6T8/+UX0UV7ZX4Suhn4sna1cecGhpO1UdxB29hUGP8SNv81FuLR/yRXU="
  file: hs-tools-$TRAVIS_TAG.tar.gz
  skip_cleanup: true
  on:
    repo: TokTok/hs-tools
    tags: true
