name: deploy-flatpak

on:
  workflow_call:
    inputs:
      project-name:
        description: 'Name of the application to build (e.g. qTox)'
        required: false
        type: string
      org-name:
        description: 'Reverse domain name of the organization to build (e.g. chat.tox)'
        required: false
        type: string
        default: 'chat.tox'
      screenshot:
        description: |
          Whether the smoke-test will output a screenshot. If true, the
          screenshot will be uploaded as an artifact. The smoke-test script
          must output the screenshot to the file named by the
          $QTOX_SCREENSHOT environment variable.
        required: false
        type: boolean
      smoke-test:
        description: 'Command to run to smoke test the AppImage'
        required: true
        type: string
      test-files:
        description: |
          List of test files needed to checkout from the repository. If your
          smoke-test script is local to the repository, it needs to be
          listed here.
        required: false
        type: string

jobs:
  build:
    name: Build
    permissions:
      contents: write
    strategy:
      matrix:
        arch: [x86_64]
    runs-on: ubuntu-24.04
    steps:
      - name: Install prerequisites
        run: sudo apt-get install -y --no-install-recommends pcregrep
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Checkout ci-tools
        if: github.repository != 'TokTok/ci-tools'
        uses: actions/checkout@v4
        with:
          repository: TokTok/ci-tools
          path: third_party/ci-tools
          submodules: true
      - name: Link ci-tools
        if: github.repository == 'TokTok/ci-tools'
        run: ln -s .. third_party/ci-tools
      - name: Checkout dockerfiles
        uses: actions/checkout@v4
        with:
          repository: TokTok/dockerfiles
          path: third_party/dockerfiles
          submodules: true
      - name: Copy docker-compose.yml
        run: cp third_party/dockerfiles/docker-compose.yml .

      - name: Determine artifact file name
        id: artifact
        run: |
          PROJECT_NAME="${{ inputs.project-name }}"
          if [ -z "$PROJECT_NAME" ]; then
            PROJECT_NAME="$(pcregrep -M -o1 'project\(\s*(\S+)' CMakeLists.txt)"
          fi
          echo "project-name=$PROJECT_NAME" >>$GITHUB_OUTPUT

          ARTIFACT="$PROJECT_NAME.flatpak"
          echo "artifact=$ARTIFACT" >>$GITHUB_OUTPUT
          echo "artifact-ref=$PROJECT_NAME-${{ github.sha }}-flatpak-${{ matrix.arch }}" >>$GITHUB_OUTPUT
          echo "binary-name=$(echo "$PROJECT_NAME" | tr '[:upper:]' '[:lower:]')" >>$GITHUB_OUTPUT
      - name: Cache flatpak-builder cache (except ccache)
        uses: actions/cache@v4
        with:
          path: |
            .flatpak-builder/cache
            .flatpak-builder/checksums
            .flatpak-builder/downloads
          key: ${{ github.job }}-flatpak-builder
      - name: Cache flatpak-builder cache (only ccache)
        uses: actions/cache@v4
        with:
          path: .flatpak-builder/ccache
          key: ${{ github.job }}-flatpak-ccache
      - name: Download Docker image
        run: docker compose run --rm flatpak uname -a
      - name: Run build
        run: docker compose run
          --rm
          flatpak
          third_party/ci-tools/platform/flatpak/build.sh
          ${{ steps.artifact.outputs.project-name }}
          ${{ inputs.org-name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact.outputs.artifact-ref }}
          path: |
            ${{ steps.artifact.outputs.artifact }}
            ${{ steps.artifact.outputs.artifact }}.sha256
          if-no-files-found: error
      - name: Get tag name for release file name
        if: contains(github.ref, 'refs/tags/v')
        id: get_version
        run: |
          VERSION="$(echo "$GITHUB_REF" | cut -d / -f 3)"
          echo "version_tag=$VERSION" >>$GITHUB_OUTPUT
          echo "release_artifact=${{ steps.artifact.outputs.project-name }}-$VERSION.${{ matrix.arch }}.flatpak" >>$GITHUB_OUTPUT
      - name: Rename artifact for release upload
        if: contains(github.ref, 'refs/tags/v')
        run: |
          cp "${{ steps.artifact.outputs.artifact }}"        "${{ steps.get_version.outputs.release_artifact }}"
          cp "${{ steps.artifact.outputs.artifact }}.sha256" "${{ steps.get_version.outputs.release_artifact }}.sha256"
      - name: Upload to versioned release
        if: contains(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          artifacts: "${{ steps.get_version.outputs.release_artifact }},${{ steps.get_version.outputs.release_artifact }}.sha256"
      - name: Rename flatpak for nightly upload
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          cp "${{ steps.artifact.outputs.artifact }}"        "${{ steps.artifact.outputs.project-name }}-nightly.flatpak"
          cp "${{ steps.artifact.outputs.artifact }}.sha256" "${{ steps.artifact.outputs.project-name }}-nightly.flatpak.sha256"
      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          artifacts: "${{ steps.artifact.outputs.project-name }}-nightly.flatpak,${{ steps.artifact.outputs.project-name }}-nightly.flatpak.sha256"

  test:
    name: Test
    needs: [build]
    strategy:
      matrix:
        arch: [x86_64]
    runs-on: ubuntu-22.04
    steps:
      - name: Install prerequisites
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends pcregrep
      - uses: actions/checkout@v4
        if: inputs.test-files
        with:
          # Fetch tags if we're not already in a tag build.
          fetch-tags: ${{ !contains(github.ref, 'refs/tags/v') }}
          sparse-checkout: ${{ inputs.test-files }}
      - name: Determine artifact file name
        id: artifact
        run: |
          PROJECT_NAME="${{ inputs.project-name }}"
          if [ -z "$PROJECT_NAME" ]; then
            PROJECT_NAME="$(pcregrep -M -o1 'project\(\s*(\S+)' CMakeLists.txt)"
          fi
          ARTIFACT="$PROJECT_NAME.flatpak"
          echo "artifact=$ARTIFACT" >>$GITHUB_OUTPUT
          echo "artifact-ref=$PROJECT_NAME-${{ github.sha }}-flatpak-${{ matrix.arch }}" >>$GITHUB_OUTPUT
          echo "binary-name=$(echo "$PROJECT_NAME" | tr '[:upper:]' '[:lower:]')" >>$GITHUB_OUTPUT
          echo "project-name=$PROJECT_NAME" >>$GITHUB_OUTPUT
      - name: Download artifact from build step
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.artifact.outputs.artifact-ref }}
      - name: Install flatpak runner
        run: sudo apt-get install -y flatpak
      - name: Install KDE runtime
        run: |
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install --user -y --noninteractive flathub org.kde.Platform/${{ matrix.arch }}/6.8
      - name: Install flatpak
        run: flatpak install --user -y --bundle ${{ steps.artifact.outputs.artifact }}
      - name: Run flatpak
        run: ${{ inputs.smoke-test }} flatpak run ${{ inputs.org-name }}.${{ steps.artifact.outputs.project-name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QT_QPA_PLATFORM: offscreen
